spring:
  application:
    name: 'discovery'
  profiles:
    active: peer2
---
spring:
  profiles: peer1
server:
  port: 8761

eureka:
  instance:
    hostname: peer1
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8762/eureka/
---
spring:
  profiles: peer2
server:
  port: 8762

eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
---
