#server:
#  port: 8761
#
#spring:
#  application:
#    name: 'discovery'
#  profiles:
#    active: peer1
#
#eureka:
#  instance:
#    hostname: peer1
#    preferIpAddress: true
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    service-url:
#      defaultZone: http://localhost:8762/eureka/


server:
  port: 8762

spring:
  application:
    name: 'discovery'
  profiles:
    active: peer2

eureka:
  instance:
    hostname: peer2
    preferIpAddress: true
    metadataMap:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${server.port}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/